### PR TITLE
Bugfixes for thomp_nc_density

### PR DESCRIPTION
**Pull request by climbfuji**
Bugfixes, performance improvements and formatting updates in `physics/GFS_suite_interstitial.F90` and `physics/GFS_rrtmgp_thompsonmp_pre.F90`

Formatting updates: remove trailing whitespaces and replace tabs with whitespaces in `physics/GFS_rrtmgp_thompsonmp_pre.F90`.

### CODE REVIEW

**Comment by climbfuji** [comment]
@tanyasmirnova please merge this PR, it works fine on Hera with Intel and GNU. Thanks!

**Comment by climbfuji** [comment]
> @tanyasmirnova please merge this PR, it works fine on Hera with Intel and GNU. Thanks!

Merci beaucoup!

**Comment by tanyasmirnova** [comment]
de nada!

**Review by tanyasmirnova — COMMENTED** [review]
@climbfuji Approved.

**Pull request merged**
