### PR TITLE
Changes in RUC LSM for fractional land/water/sea-ice mask.

### PR DESCRIPTION
**Pull request by tanyasmirnova**
For this initial implementation of fractional land mask, RUC LSM will be called
only for land points. Sea ice points will be covered with the call to sfc_sice.
Also, this commit removes sending top 4 levels of RUC soil variables to the 4-layer Noah variables.
This was done on the early stages of RUC LSM implementation to see RUC soil variables in the model output.

### CODE REVIEW

**Comment by climbfuji** [comment]
@tanyasmirnova this PR points to your master as target, not the NCAR master. Do you want me to change this?

**Comment by tanyasmirnova** [comment]
Dom,
This is an old PR, and it is not needed after you merged RUC LSM changes for fractional land mask.
Thanks,
Tanya

**Comment by climbfuji** [comment]
... it's pointing to the wrong master anyway, so do you mind closing it or have me closing it?

**Comment by tanyasmirnova** [comment]
This PR is closed.

**Pull request closed without merging**
